#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
gotoxy(12,11);
cout<<"                         *           ";
gotoxy(12,12);
cout<<"                        ***          ";
gotoxy(12,13);
cout<<"                       *****         ";
gotoxy(12,14);
cout<<"                      *******        ";
gotoxy(12,15);
cout<<"                     *********  ";
gotoxy(12,16);
cout<<"                      ******* ";
gotoxy(12,17);
cout<<"                       *****  ";
gotoxy(12,18);
cout<<"                        ***  ";
gotoxy(12,19);
cout<<"                         * ";
getch();
}